#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=8
#SBATCH -t 6:00:00

b=$SAMPLE

# Container path remains the same for anyone running on the MCC cluster
container=/share/singularity/images/ccs/conda/amd-conda15-rocky8.sinf

# The number of CPUs or threads
THR=8

#---------------------------------------------------------
# MetaPhlAn analysis

echo "==[ 1.metaphlan_analysis: $(date) ]" ;
cd $FOLDER/1.metaphlan_analysis ;

singularity run --app metaphlan410 --env METAPHLAN_DB_DIR=/share/apps/amd/MetaPhlAn/databases/ $container metaphlan ../04.trimmed_fasta/"$b".CoupledReads.fa --input_type fasta --bowtie2out ./"$b".bowtie2.bz2 --nproc $THR -o ./"$b"_profile.txt



#---------------------------------------------------------

#---------------------------------------------------------

echo "Done: $(date)." ;
