#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=24
#SBATCH -t 6:00:00

b=$SAMPLE

# Container path remains the same for anyone running on the MCC cluster
container=/share/singularity/images/ccs/conda/amd-conda18-rocky8.sinf

# The number of CPUs or threads
THR=24

#---------------------------------------------------------
# MetaPhlAn analysis

echo "==[ 06.kraken: $(date) ]" ;
cd $FOLDER/06.kraken ;

mv ../database . ;

singularity run --app kraken22132 $container kraken2 --db ./database --threads $THR --report ./"$b"_k2_report.txt --paired ../04.trimmed_fasta/"$b".CoupledReads.fa

#---------------------------------------------------------

echo "Done: $(date)." ;
