#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH -t 2:00:00

b=$SAMPLE

# Change enveomics path to yours 
enve=/project/mki314_uksr/enveomics/Scripts

# Source path to Conda environments
source /project/mki314_uksr/miniconda3/etc/profile.d/conda.sh

# The number of CPUs or threads
THR=4

#---------------------------------------------------------
# Run DeepARG

echo "==[ 12.deeparg: $(date) ]" ;
cd $FOLDER/12.deeparg ;

conda activate deeparg

deeparg predict --model LS -i $FOLDER/16.checkm2/output/good_quality/"$b".fa -o ./"$b" -d $FOLDER/12.deeparg/database 

conda deactivate

#---------------------------------------------------------

echo "Done: $(date)." ;
