#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=8
#SBATCH -t 24:00:00

b=$SAMPLE

# Change enveomics path to yours 
enve=/project/mki314_uksr/enveomics/Scripts

# Source path to Conda environments
source /project/mki314_uksr/miniconda3/etc/profile.d/conda.sh

# Container path remains the same for anyone running on the MCC cluster (unless path has been updated)
container=/share/singularity/images/ccs/conda/amd-conda23-rocky9.sinf

# The number of CPUs or threads
THR=8

#---------------------------------------------------------

echo "==[ 20.amr_finder: $(date) ]" ;
cd $FOLDER/20.amr_finder ;

conda activate amr-finder

amrfinder -p test_prot.fa -g test_prot.gff -n test_dna.fa -O Escherichia --plus

conda deactivate

#---------------------------------------------------------

echo "Done: $(date)." ;
