#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH -t 6:00:00

b=$SAMPLE

# Source path to Conda environments
source /project/mki314_uksr/miniconda3/etc/profile.d/conda.sh

# The number of CPUs or threads
THR=4

#---------------------------------------------------------
# MetaPhlAn analysis

conda activate bakta

echo "==[ 14.bakta: $(date) ]" ;
cd $FOLDER/14.bakta ;

bakta --db bakta_db "$b".fa

conda deactivate

#---------------------------------------------------------

echo "Done: $(date)." ;
