#!/bin/bash
#SBATCH -J mash
#SBATCH --account=coa_mki314_uksr
#SBATCH --partition=normal
#SBATCH --ntasks=4
#SBATCH -t 12:00:00
#SBATCH --error mash-%j.err
#SBATCH -o mash-%j.out

enve=/project/mki314_uksr/enveomics/Scripts
THR=4
mash=/project/mki314_uksr/Software/mash-Linux64-v2.3/mash

cd /scratch/jwme229/raw_data_files/07.mash

readlink -f *.msh > mash_list.txt ;

echo "List created"

"$mash" paste mash.all -l mash_list.txt ;

echo "ready to make distance matrix"

"$mash" dist -t mash.all.msh mash.all.msh > Mash_dist.txt ;

echo "Done"
