#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH --mem=80g
#SBATCH -t 12:00:00

b=$SAMPLE

# Change enveomics and mash paths to yours 
enve=/project/mki314_uksr/enveomics/Scripts
mash=/project/mki314_uksr/Software/mash-Linux64-v2.3/mash

# The number of CPUs or threads | Maximum RAM usage in Mib
THR=4
MEM=76293

#---------------------------------------------------------
# Run Nonpareil

echo "==[ 08.nonpareil: $(date) ]" ;
cd $FOLDER/08.nonpareil ;

source /project/mki314_uksr/miniconda3/etc/profile.d/conda.sh
conda activate nonpareil

if [[ -s "../04.trimmed_fasta/$b.SingleReads.fa" ]] ; then
   echo "Single Reads!"
   nonpareil -s ../04.trimmed_fasta/"$b".SingleReads.fa -T kmer alignment -f fasta -R $MEM -t $THR -b "$b".nonpareil.out
else
   echo "Coupled Reads! Should use only one pair reads"
   nonpareil -s ../04.trimmed_fasta/"$b"_1.fa -T kmer alignment -f fasta -R $MEM -t $THR -b "$b".nonpareil.out
fi

#---------------------------------------------------------
# Run Mash sketch

echo "==[ 09.mash: $(date) ]" ;
cd $FOLDER/09.mash ;

"$mash" sketch $FA -o $b.msh -k 25 -s 1000000  ;

#---------------------------------------------------------

echo "Done: $(date)."
