#!/bin/bash
#$ -e /account/mkim/
#$ -o /account/mkim/

source /project/mki314_uksr/miniconda3/etc/profile.d/conda.sh
conda activate CheckM

enve=/project/mki314_uksr/enveomics/Scripts
FA=/scratch/jwme229/Software/FastANI/fastANI
THR=8

#---------------------------------------------------------

echo "==[ 17.checkm: $(date) ]"

cd $FOLDER/17.checkm

for fname in *; do
  name="${fname%\.*}"
  extension="${fname#$name}"
  newname="${name//./_}"
  newfname="$newname""$extension"
  if [ "$fname" != "$newfname" ]; then
    echo mv "$fname" "$newfname"
    mv "$fname" "$newfname"
  fi
done

mkdir output

checkm lineage_wf -t $THR -x fasta --tab_table -f ./output/qs.o1.tsv  ./ ./output

awk -F "\t" '{x=$12; y=$13 * 5} {if (x - y >= 50) print $0}' ./output/qs.o1.tsv > ./output/high_qual.tsv

awk -F "\t" '{x = $12 - $13 * 5} {$(NF+1)=x;}1' OFS="\t" ./output/high_qual.tsv > ./output/high_qual_w_score.tsv

awk '{print $1}' ./output/high_qual_w_score.tsv > ./output/list.txt

mkdir ./output/good_quality

mv ./output/high_qual_w_score.tsv ./output/good_quality

while IFS= read -r line
do 
   cp ./"$line".fasta ./output/good_quality
done < ./output/list.txt

gzip *.fasta 

#---------------------------------------------------------



#---------------------------------------------------------

echo "Done: $(date)."


