#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH -t 12:00:00


b=$SAMPLE
enve=/project/mki314_uksr/enveomics/Scripts
THR=6

source /project/mki314_uksr/miniconda3/etc/profile.d/conda.sh
conda activate dRep

#---------------------------------------------------------

mkdir $FOLDER/18.drep/$b/output

cd $FOLDER/17.checkm/$b/output/good_quality

dRep compare $FOLDER/18.drep/$b/output/compare -p PROCESSORS $THR -g $FOLDER/17.checkm/$b/output/good_quality/*.fa --S_algorithm fastANI

cd $FOLDER/17.checkm/$b/output/good_quality

dRep dereplicate $FOLDER/18.drep/$b/output/dereplicate -p PROCESSORS $THR -g $FOLDER/17.checkm/$b/output/good_quality/*.fa --S_algorithm fastANI

#---------------------------------------------------------

conda deactivate

echo "Done: $(date)."
