#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH -t 12:00:00


b=$SAMPLE
enve=/project/mki314_uksr/enveomics/Scripts
THR=10

source /project/mki314_uksr/miniconda3/etc/profile.d/conda.sh
conda activate CheckM

#---------------------------------------------------------

checkm lineage_wf -t $THR -x fa --tab_table ./ ../17.checkm/$b

conda deactivate

#---------------------------------------------------------

echo "Done: $(date)."