#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=6
#SBATCH -t 12:00:00


b=$SAMPLE
enve=/project/mki314_uksr/enveomics/Scripts
THR=6

source /project/mki314_uksr/miniconda3/etc/profile.d/conda.sh
conda activate dRep

#---------------------------------------------------------

mkdir $FOLDER/18.dRep/$b/output

cd $FOLDER/16.checkm2/$b/good_quality

dRep compare $FOLDER/18.dRep/$b/output/compare -p $THR -g $FOLDER/16.checkm2/$b/good_quality/*.fa --S_algorithm fastANI

cd $FOLDER/16.checkm2/$b/good_quality

dRep dereplicate $FOLDER/18.dRep/$b/output/dereplicate -p $THR -g $FOLDER/16.checkm2/$b/good_quality/*.fa --S_algorithm fastANI

#---------------------------------------------------------

conda deactivate

echo "Done: $(date)."
