#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH -t 12:00:00


b=$SAMPLE
enve=/project/mki314_uksr/enveomics/Scripts
THR=16

source /project/mki314_uksr/miniconda3/etc/profile.d/conda.sh
conda activate CheckM

#---------------------------------------------------------

mkdir $FOLDER/17.checkm/$b/output

checkm lineage_wf -t $THR -x fa --tab_table -f $FOLDER/17.checkm/$b/output/qs.o1.tsv ./ $FOLDER/17.checkm/$b

cd $FOLDER/17.checkm

awk -F "\t" '{x=$12; y=$13 * 5} {if (x - y >= 50) print $0}' ./$b/output/qs.o1.tsv > ./$b/output/high_qual.tsv

awk -F "\t" '{x = $12 - $13 * 5} {$(NF+1)=x;}1' OFS="\t" ./$b/output/high_qual.tsv > ./$b/output/high_qual_w_score.tsv

awk '{print $1}' ./$b/output/high_qual_w_score.tsv > ./$b/output/list.txt

mkdir ./$b/output/good_quality

mv ./$b/output/high_qual_w_score.tsv ./$b/output/good_quality

while IFS= read -r line
do
   cp ./$b/"$line".fa ./$b/output/good_quality
done < ./$b/output/list.txt

gzip *.fa

conda deactivate

#---------------------------------------------------------

echo "Done: $(date)."