#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=60
#SBATCH -t 12:00:00


b=$SAMPLE
enve=/project/mki314_uksr/enveomics/Scripts
THR=60

source /project/mki314_uksr/miniconda3/etc/profile.d/conda.sh
conda activate gtdbtk-2.4.0

# Container path remains the same for anyone running on the MCC cluster
container=/share/singularity/images/ccs/conda/amd-conda15-rocky8.sinf
database=/share/examples/MCC/gtdbtk/release220:/gtdbtk_data/database

#---------------------------------------------------------

echo "==[ 17.checkm: $(date) ]"

cd $FOLDER/17.checkm/$b/output/good_quality

readlink -f *.fa > list.txt

cat list.txt |  awk '{print $NF}' FS=/ | sed -e 's/\.fasta$//' > ID.txt

paste list.txt ID.txt > batchfile.txt

mkdir $FOLDER/18.gtdbtk/$b/

singularity run --env GTDBTK_DATA_PATH=/gtdbtk_data/database -B $database --app gtdbtk240 $container gtdbtk classify_wf --batchfile $FOLDER/17.checkm/$b/output/good_quality/batchfile.txt --out_dir $FOLDER/18.gtdbtk/$b/ --mash_db ../09.mash/"$b".msh --extension fa --cpus $THR

cd $FOLDER/18.gtdbtk/$b/

for file in $FOLDER/18.gtdbtk/$b/* ; do
   base=$(basename $file) ;
   mv "$base" $FOLDER/18.gtdbtk/combined/"$b"_"$base";
done

# gtdbtk classify_wf --batchfile ./batchfile.txt --out_dir $FOLDER/18.gtdbtk/$b/ --mash_db ../09.mash/"$b".msh --extension fa --cpus $THR

#----------------------------------------------------------

conda deactivate

echo "Done: $(date)."
