#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH -t 12:00:00


b=$SAMPLE
enve=/project/mki314_uksr/enveomics/Scripts
THR=6

source /project/mki314_uksr/miniconda3/etc/profile.d/conda.sh
conda activate dRep

#---------------------------------------------------------

mkdir $FOLDER/18.drep/$b/output

cd $FOLDER/17.checkm/$b/output/good_quality

dRep $FOLDER/18.drep/$b/output -p PROCESSORS $THR -g $FOLDER/17.checkm/$b/output/good_quality/ --S_algorithm fastANI