#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH -t 12:00:00

b=$SAMPLE

# Change enveomics path to yours 
enve=/project/mki314_uksr/enveomics/Scripts

# The number of CPUs or threads
THR=4

#---------------------------------------------------------
# Quality trimming

echo "==[ 02.trimmed_reads: $(date) ]" ;
cd "$FOLDER/02.trimmed_reads" ;

echo $PATH

source /project/mki314_uksr/miniconda3/etc/profile.d/conda.sh

conda activate trim-galore

if [[ -e ../01.raw_reads/"$b".2.fastq ]] ; then
   trim_galore -q 20 --fastqc --stringency 3  --length 50 -o ./ --cores $THR --paired ../01.raw_reads/"$b".1.fastq ../01.raw_reads/"$b".2.fastq
else
   trim_galore -q 20 --fastqc --stringency 3  --length 50 -o ./ --cores $THR ../01.raw_reads/"$b".1.fastq
fi ;

conda deactivate

#---------------------------------------------------------
# Filter human reads

conda activate hocort

if [[ -e ./"$b".2_val_2.fq ]] ; then
   hocort map bowtie2 -x $FOLDER/human_genome/GRCh38_p14 -i ./"$b".1_val_1.fq ./"$b".2_val_2.fq -o ../hocort_out/"$b".filter_1.fq ../hocort_out/"$b".filter_2.fq
else
   hocort map bowtie2 -x $FOLDER/human_genome/GRCh38_p14 -i ./"$b".1_val_1.fq -o ../hocort_out/"$b".filter_1.fq
fi ;

conda deactivate

#---------------------------------------------------------
# Tagging fastq

conda activate ruby

if [[ -e ../hocort_out/"$b".filter_2.fq ]] ; then
   $enve/FastQ.tag.rb -i ../hocort_out/"$b".filter_1.fq -p "$b-" -s "/1" -o "$b".1.tagged.fastq ;
   $enve/FastQ.tag.rb -i ../hocort_out/"$b".filter_2.fq -p "$b-" -s "/2" -o "$b".2.tagged.fastq ;
else
   $enve/FastQ.tag.rb -i ../hocort_out/"$b".filter_1.fq -p "$b-" -s "/1" -o "$b".1.tagged.fastq ;
fi

#---------------------------------------------------------
# FastQ -> FastA 

FQ2A="$enve/FastQ.toFastA.awk" ;
echo "==[ 04.trimmed_fasta: $(date) ]" ;
cd $FOLDER/04.trimmed_fasta ;

if [[ -e ../02.trimmed_reads/"$b".2.tagged.fastq ]] ; then
   awk -f "$FQ2A" < ../02.trimmed_reads/"$b".1.tagged.fastq > "$b"_1.fa ;
   awk -f "$FQ2A" < ../02.trimmed_reads/"$b".2.tagged.fastq > "$b"_2.fa ;
else
   awk -f "$FQ2A" < ../02.trimmed_reads/"$b".1.tagged.fastq  > "$b"_SingleReads.fa ;
fi ;

#---------------------------------------------------------
# Interpose fasta

if [[ -e "$b"_2.fa ]] ; then
   $enve/FastA.interpose.pl "$b".CoupledReads.fa "$b"_1.fa "$b"_2.fa ;
else
   mv "$b"_SingleReads.fa "$b".SingleReads.fa ;
fi ;

#---------------------------------------------------------

echo "Done: $(date)." ;
